name: Atefahmed Action
description: A GitHub Action that performs a specific task using a Docker Image
author: P10-ai
branding:
  icon: activity
  color: blue
inputs:
  openapi_spec_url:
    description: Open API Spec File
    required: true
    default: 'https://petstore.swagger.io/v2/swagger.yaml'
runs:
  using: 'docker'
  image: docker://docker.pkg.github.com/atefahmed/perfai-atefahmed-private:main
  
